export * from "./IStrategy";
export * from "./AuchanStrategy";
export * from "./DeliveryClubStrategy";
export * from "./KuperStrategy";
export * from "./MagnitStrategy";
export * from "./OzonStrategy";
export * from "./PerekrestokStrategy";
export * from "./PyaterochkaStrategy";
export * from "./SamokatStrategy";
